.MODEL SMALL
.DATA
; Input data
	RECORD DB 3 DUP (10100000B, 01001100B, 01110000B) ; 08:04 - 01:48
	RATES DW 2 DUP (10000011B, 00010000B)	; 00 - 24, 0.32 
; Output data
	DURATION_OF_CONNECTION DW ?
	COST_TO_BE_CHARGED DW ? 
; Work variables
	START_MIN DW ?
	END_MIN DW ?
	START_RATE1 DW ?
	START_RATE2 DW ?
	END_RATE1 DW ?
	END_RATE2 DW ?
	DURATION DW ?
	COST DW ?
.STACK
.CODE
.STARTUP

MAIN PROC
	CALL HOUR_TO_MIN
;	CALL MANAGE_NEXT_DAY
	CALL DURATION_CALCULATION
	
	RET
MAIN ENDP
.EXIT

HOUR_TO_MIN PROC
	PUSH AX
	PUSH BX
	PUSH CX
	PUSH DX
	
	MOV AH, RECORD+1
	MOV AL, RECORD		; ssssDEEEXSSSSSss
    ; ROR AX, 2
	ROR AX, 1
	ROR AX, 1			; ssssssDEEEXSSSSS
	; SHR AH, 2
	SHR AH, 1
	SHR AH, 1			; 00ssssss
	XOR CH, CH
	MOV CL, AH			; 00ssssss

	XOR AH, AH
	AND AL, 1FH			; 000SSSSS
	MOV BX, 60			; Minutes in an hour
	MUL BL				; AX = Minutes * 60
	ADD AX, CX
	MOV START_MIN, AX
	
	MOV AH, RECORD+2
	MOV AL, RECORD+1	; EEeeeeeessssDEEE
	; ROL AX, 2
	ROL AX, 1
	ROL AX, 1			; eeeeeessssDEEEEE
	; SHR AH, 2
	SHR AH, 1
	SHR AH, 1			; 00eeeeee
	XOR CH, CH
	MOV CL, AH			; 00eeeeee

	XOR AH, AH
	AND AL, 1FH			; 000EEEEE
	MOV BX, 60			; Minutes in an hour
	MUL BL				; AX = Minutes * 60
	ADD AX, CX
	MOV END_MIN, AX
	
	POP DX
	POP CX
	POP BX
	POP AX
	RET
HOUR_TO_MIN ENDP
                         
DURATION_CALCULATION PROC
	PUSHA
	
	MOV AX, END_MIN
	SUB AX, START_MIN
	MOV DURATION, AX
	; AX contains the duration in minutes
	MOV CL, RECORD+1	; ssssDEEE
	TEST CL, 08H		; 00001000
	JZ SAME_DAY
    ADD AX, 1440
    
SAME_DAY:
	MOV BX, 60
	DIV BL
	; AL contains the hours
	; AH contains the minutes
	; 00MMMMMM 000HHHHH
	MOV BH, AL
	ROR BH, 1
	ROR BH, 1
	OR AH, BH
	SHR AL, 1
	SHR AL, 1
	SHR AL, 1
	OR AL, 11111000B	; 11111HHH
	MOV DURATION_OF_CONNECTION, AX	
		
	POPA
	RET
DURATION_CALCULATION ENDP
                   
.EXIT
END