; Computer Architectures
; Lab 04 - Exercise 02
#start=8259.exe#
PORTA	EQU	80H
PORTB	EQU	PORTA+1
PORTC	EQU	PORTA+2
CONTROL	EQU	PORTA+3
PIC		EQU	40H

MAX		EQU	40	; 40 Chars maximum

.MODEL small
.STACK
.DATA
	MYNUMBER	DD	?
.CODE
.STARTUP
	CLI
	MOV MYNUMBER, 1234H
	MOV MYNUMBER+2, 5678H
	CALL INIT_8255
	CALL INIT_8259
	CALL INIT_IVT
	STI	
.EXIT

INIT_8255	PROC
	PUSH AX
	PUSH DX
	MOV DX, CONTROL
	MOV AL, 10100000B	;	Group A Mode 1 Output
	OUT DX, AL
	MOV AL, 00001101B	;	Interrupt for group A
	OUT DX, AL
	POP DX
	POP AX
	RET
INIT_8255	ENDP

INIT_8259	PROC
	PUSH AX
	PUSH DX
	; ICW 1
	MOV DX, PIC
	MOV AL, 00010011B
	OUT DX, AL
	; ICW 2
	MOV DX, PIC+1
	MOV AL, 00100000B	;	ISR Address
	OUT DX, AL
	; ICW 4
	MOV AL, 00000011B
	OUT DX, AL
	; OCW 1
	MOV AL, 01111111B	;	CH7 Enabled (Port A)
	OUT DX, AL
	POP DX
	POP AX
	RET	
INIT_8259	ENDP

INIT_IVT	PROC
	PUSH AX
	PUSH BX
	PUSH DX
	PUSH DS
	
	XOR AX, AX
	MOV DS, AX
	MOV BX, 00100111B
	SHL BX, 1
	SHL BX, 1
	MOV AX, OFFSET ISR_PA_OUT
	MOV DS:[BX], AX
	MOV AX, SEG ISR_PA_OUT
	MOV DS:[BX+2], AX
	
	POP DS
	POP DX
	POP BX
	POP AX
	RET
INIT_IVT	ENDP

ISR_PA_OUT	PROC
	PUSH AX
	PUSH DX
	MOV DX, PORTA
	MOV AL, BYTE PTR MYNUMBER+2
	OUT DX, AL
	MOV AL, BYTE PTR MYNUMBER+3
	OUT DX, AL	
	MOV AL, BYTE PTR MYNUMBER
	OUT DX, AL	
	MOV AL, BYTE PTR MYNUMBER+1
	OUT DX, AL	
	POP DX           
	POP AX
	IRET
ISR_PA_OUT	ENDP		